# This is a basic workflow to help you get started with Actions

name: CI
env:
  PROJECT_NAME: PointCloudSegmentation
  BUILD_DIR:    docker-env 
  VK_ME:        136761433
  VK_ILYA:      75560006
  VK_POLINA:    132293451
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codeStyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
      env:  
        PRECOMMAND_MESSAGE: Vaba Laba Dab Dab!
  
    - name: CodeStyle VK Notify
      uses: alphamusic/VK-Notifications@1.0.2
      env: 
         VK_USERS :  $VK_ME #, 75560006, 132293451
         VK_MESSAGE: "Hi! The code style cheker is passed"
         VK_TOKEN: ${{ secrets.VK_TOKEN }}   
    
  build:
    runs-on: ubuntu-latest
    needs: codeStyle
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Docker version
        run: docker -v
      
      - name: Docker build
        run: |
              docker build -t $PROJECT_NAME:ver_$GITHUB_RUN_NUMBER $BUILD_DIR
              docker images 
         
      - name: DockerBuild VK Notify
        uses: alphamusic/VK-Notifications@1.0.2
        env: 
          VK_USERS :  $VK_ME #, 75560006, 132293451
          VK_MESSAGE: "And... docker build step is successfuly passed!"
          VK_TOKEN: ${{ secrets.VK_TOKEN }}   
