# This is a basic workflow to help you get started with Actions

name: CI

env:
  PROJECT_NAME: point_cloud_segmentation
  BUILD_DIR:    docker-env

on:
  push: 
    branches: [ master]
  
  pull_request:
    branches: [ master ]

jobs:
  codeStyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
      env:  
        PRECOMMAND_MESSAGE: Vaba Laba Dab Dab!
  
    - name: CodeStyle VK Notify
      uses: alphamusic/VK-Notifications@1.0.2
      env: 
         VK_USERS :  ${{ secrets.VK_ME }} 
         VK_MESSAGE: Hi!
                     The code style cheker is passed for ${GITHUB_REF:11}
         VK_TOKEN: ${{ secrets.VK_TOKEN }}   
    
  build:
    runs-on: ubuntu-latest
    needs: codeStyle
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Docker version
        run: docker -v
      
      - name: Docker build
        run: |
              docker build -t $PROJECT_NAME:${GITHUB_REF:11} $BUILD_DIR
              docker images 
         
      - name: DockerBuild VK Notify
        uses: alphamusic/VK-Notifications@1.0.2
        env: 
          VK_USERS :  ${{ secrets.VK_ME }} 
          VK_MESSAGE: And... docker build ${GITHUB_REF:11} is successfuly passed!
          VK_TOKEN: ${{ secrets.VK_TOKEN }}   
      
      - name: Docker Upload
        run: |
             docker login --username=${{ secrets.DOCKER_LOGIN }} --password=${{ secrets.DOCKER_PASSWORD}}
             docker push  vadikalp/point_cloud_sementation:$PROJECT_NAME:${GITHUB_REF:11}
             
      - name: Docker Push VK Notify
        uses: alphamusic/VK-Notifications@1.0.2
        env: 
          VK_USERS :  ${{ secrets.VK_ME }} 
          VK_MESSAGE: Finally, docker build ${GITHUB_REF:11} uploaded to docker hub! Hell yeah!
          VK_TOKEN: ${{ secrets.VK_TOKEN }}   
