# This is a basic workflow to help you get started with Actions

name: CI
env:
  PROJECT_NAME: PointCloudSegmentation
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  codeStyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
      env:  
        PRECOMMAND_MESSAGE: Vaba Laba Dab Dab!
  
    - name: VK Notifications
      uses: alphamusic/VK-Notifications@1.0.2
      env: 
         VK_USERS :  136761433 #, 75560006, 132293451
         VK_MESSAGE: "Hi! The code style cheker is passed"
         VK_TOKEN: ${{ secrets.VK_TOKEN }}   
    
  build:
    runs-on: ubuntu-latest
    needs: codeStyle
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Docker version
        run: docker -v
      
      - name: Docker build
        run: |
              docker build -t ${{ secrets.USERNAME }}/$PROJECT_NAME/docker-env:ver_$GITHUB_RUN_NUMBER
              docker images 
     
